apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  description: custom
  name: customised-system
  project: giri-nov
spec:
  artifact:
    artifact:
      configmap:
        name: file://customised-system/alertmanager-configMap.yaml
      configuration:
        name: file://customised-system/alertmanager-configuration.yaml
      secret:
        name: file://customised-system/alertmanager-secret.yaml
      statefulset:
        name: file://customised-system/alertmanager-statefulSet.yaml
    type: AlertManager
  sharing: {}
  version: v1
