apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: nginx-upload
  project: giri-nov
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nginx-upload/nginx-15.4.2.tgz
      valuesPaths:
      - name: file://artifacts/nginx-upload/values.yaml
    type: Helm
  namespace: nginx
  sharing: {}
  version: v1
