apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: giri
  name: giri
  project: giri-nov
spec:
  drift:
    action: Deny
    enabled: true
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-jan2-demo2
