apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  project: giri-nov
spec:
  artifact:
    artifact: {}
    type: Helm
  namespace: giri
