apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: nginx
  project: giri-nov
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nginx/nginx-15.4.2.tgz
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: jan19
  placement:
    selector: rafay.dev/clusterName=giri-jan18
  version: nginx-v1-202401190422010000
