apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: sample-web
  project: giri-nov
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/sample-web/sample-web.yaml
    type: Yaml
  namespace: cilium-test
  placement:
    selector: rafay.dev/clusterName=giri-qc-jan10
  version: sample-web-v1-202401101108220000
