apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    chart: prometheus-11.0.2
    component: alertmanager
    heritage: Helm
    release: rafay-prometheus
    user: giri
  name: custom-configmap-alertmanager
