apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: cilium-bp
  project: giri-nov
spec:
  base:
    name: default-aks
    version: 2.3.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  networkPolicy:
    profile:
      name: default
      version: latest
  type: custom
  version: v2-aks
