apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: custom-v1
  project: giri-nov
spec:
  base:
    name: gold-v1
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
