apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: git-custom
  project: giri-nov
spec:
  base:
    name: gold-no-opa
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  opaPolicy:
    opaPolicy:
    - name: policy-privileged
      version: version-1705555677
    profile:
      name: default
      version: latest
  type: custom
  version: v1
