apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: gold-v1
  project: giri-nov
spec:
  base:
    name: default-aks
    version: 2.4.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  opaPolicy:
    opaPolicy:
    - name: policy-restricted
      version: version-1705640554
    profile:
      name: default
      version: latest
  type: golden
  version: v1
