apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: managed
  project: giri-nov
spec:
  base:
    name: minimal
    version: 2.3.0
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Managed
  type: custom
  version: v1
