apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  description: v1-test
  name: system-pipeline
  project: giri-nov
spec:
  base:
    name: default-aks
    version: 2.3.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook: {}
  namespaceConfig:
    enableSync: true
    syncType: Unmanaged
  networkPolicy:
    policies:
    - name: cp1
      version: v1
    profile:
      name: default
      version: latest
  opaPolicy:
    opaPolicy:
    - name: policy-privileged
      version: version-1703587649
    profile:
      name: default
      version: latest
  type: golden
  version: gold-v1
