apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: unmanaged-1
  project: giri-nov
spec:
  base:
    name: default
    version: 2.4.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Unmanaged
  type: custom
  version: v1
