apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: giri-jan
  project: giri-nov
spec:
  agents:
  - name: giri-agent
  credentials:
    password: sealed://credentials.password
    username: giri-rafay
  endpoint: https://github.com/giri-rafay/giri-jan.git
  secret:
    name: file://artifacts/giri-jan/sealed-secret.yaml
  type: Git
